api_platform:
    title: 'API karimmoussouni.fr'
    description: 'API Site and Blog'
    version: '1.0.0'
    show_webby: true
    name_converter: ~
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
#            - '%kernel.project_dir%/config/packages/api_platform' # yaml or xml directory configuration
    patch_formats:
        json: ['application/json']
        csv: ['text/csv']

    path_segment_name_generator: 'api_platform.path_segment_name_generator.underscore'
    allow_plain_identifiers: false
    doctrine:
        enabled: true
    doctrine_mongodb_odm:
        enabled: false
    eager_loading:
        enabled: true
        fetch_partial: false
        max_joins: 30
        force_eager: true

    enable_fos_user: false
    enable_nelmio_api_doc: false
    enable_swagger: true
    enable_swagger_ui: true
    enable_re_doc: true
    enable_entrypoint: true
    enable_docs: true
    enable_profiler: true
    oauth:
        enabled: false
        clientId: ''
        clientSecret: ''
        type: 'oauth2'
        flow: 'application'
        tokenUrl: '/oauth/v2/token'
        authorizationUrl: '/oauth/v2/auth'
        scopes: []

    graphql:
        enabled: false
        default_ide: 'graphiql'
        graphiql:
            enabled: true
        graphql_playground:
            enabled: true
        collection:
            pagination:
                enabled: true
        nesting_separator: _

    elasticsearch:
        enabled: false
        hosts: []
        mapping: []

    swagger:
        versions: [2, 3]
        api_keys: []

    collection:
        exists_parameter_name: 'exists'
        order: 'ASC'
        order_parameter_name: 'order'
        pagination:
            enabled: true
            client_enabled: false
            client_items_per_page: false
            items_per_page: 30
            maximum_items_per_page: 10
            page_parameter_name: 'page'
            enabled_parameter_name: 'pagination'
            items_per_page_parameter_name: 'itemsPerPage'
            partial: false
            client_partial: false
            partial_parameter_name: 'partial' # Default value

    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'

    http_cache:
        etag: true
        max_age: 3600
        shared_max_age: 3600
        vary: ['Accept']
        public: ~
        invalidation:
            enabled: false
            varnish_urls: []
            request_options: []

    # The list of exceptions mapped to their HTTP status code.
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST

    # The list of enabled formats. The first one will be the default.
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']
        jsonld:
            mime_types: ['application/ld+json']
