twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
#    paths: '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates'
    globals:
        ga_tracking: 'UA-xxxxx-x'
        mail: 'lebondev@gmail.com'