vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
        projects:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
#            namer: Vich\UploaderBundle\Naming\OrignameNamer