version: '3.6'

services:
    memcached:
        image: memcached:alpine
        container_name: memcached
        ports:
            - "11211:11211"
    db:
        image: mysql:5.7
        container_name: db
        privileged: true
#        user: "1000:50"
        ports:
            - "${MYSQL_ROOT_PORT}:3306"
        environment:
            MYSQL_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_PORT: ${MYSQL_ROOT_PORT}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_ROOT_PORT: ${MYSQL_ROOT_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - .data/mysql:/var/lib/mysql:rw
    php:
        env_file:
            - .env
        build:
            context: docker/php7-fpm
            dockerfile: Dockerfile
            args:
                PHP_TAG: $PHP_TAG
                XDEBUG_ENABLE: $XDEBUG_ENABLE
        container_name: php
        ports:
            - "9000:9000"
            - "3000:3000"
        extra_hosts:
            - host.docker.internal:${DOCKER_INTERNAL_IP}
        links:
            - db
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony/:rw
    nginx:
        build:
            context: docker/nginx
            dockerfile: Dockerfile
        container_name: nginx
        env_file:
            - .env
        links:
            - php
        ports:
            - ${NGINX_EXPOSE}:80/tcp
            - 443:443/tcp
        volumes:
            - nginx-log:/var/log/nginx
            - ${SYMFONY_APP_PATH}:/var/www/symfony/:rw

volumes:
    db-data:
    elastica-data:
    nginx-log:
