resources:
  App\Entity\Article: ~
  App\Entity\MediaObject: ~
  App\Entity\Project:
    shortName: 'Project'                   # optional
    description: 'A project from my customer/brain' # optional
#    iri: 'http://schema.org/Project'       # optional
    attributes:                          # optional
      pagination_items_per_page: 25    # optional
  App\Entity\Quotation:
  App\Entity\Users: ~
