App\Entity\Radar:
  attributes:
    id:
      groups: ['api_front']
    name:
      groups: ['api_front']
    speed:
      groups: ['api_front']
    longitude:
      groups: ['api_front']
    latitude:
      groups: ['api_front']
    createdAt:
      groups: ['api_front']
    updatedAt:
      groups: ['api_front']

