ARG ELK_VERSION_TAG

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION_TAG}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

#RUN wget https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.6.2-linux-x86_64.tar.gz
#RUN tar xzvf filebeat-6.6.2-linux-x86_64.tar.gz
#RUN cd filebeat-6.6.2-linux-x86_64/


#RUN bin/elasticsearch-plugin install ingest-geoip
#RUN bin/elasticsearch-plugin install ingest-user-agent
