ARG ELK_VERSION_TAG

FROM docker.elastic.co/logstash/logstash:${ELK_VERSION_TAG}

#RUN logstash-plugin install logstash-filter-json
#RUN logstash-plugin install logstash-input-gelf
#RUN logstash-plugin install logstash-input-beats
